# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2 
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
    - name: Publish app
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        source: build
        target: ${{ TARGET_DIR }}
      
    - name: Run a one-line script
      run: echo Done!
