# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2 
    - name: Publish app
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        source: /home/runner/work/personal_web/personal_web/*
        target: /var/www/personal
        strip_components: 5:  
      
    - name: Run a one-line script
      run: echo Done!
