# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: Copy sources
      run: |
        mkdir build
        cp -r source/. build/ 
    - name: Upload files to remote host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        source: build
        target: ${{ secrets.TARGET_DIR }}
        strip_components: 1
      
    - name: Finish
      run: echo Done!
